config/routes.rb
Rails.application.routes.draw do
  resources :reports

  root to: 'visitors#report'
  devise_for :users
  resources :users
  get '/oauth2callback' => 'reports#outh_response', as: 'reports_outh'
  get '/report'	=> 'visitors#report', as: 'vistors_reports'
end

app/models/report.rb
class Report < ActiveRecord::Base
	extend Legato::Model

  metrics :pageviews, :uniquePageviews, :sessions, :users, :newUsers, :exits
  dimensions :pagePathLevel1, :sessionCount, :userType, :userDefinedValue, :operating_system, :browser

  filter(:by_index_in_path_level_1) {|page_path_level1| contains(:pagePathLevel1, 'index')}

  # all reuslts query
  def self.query(profile, start_date, end_date)
    Report.results(profile,
                      :start_date => start_date,
                      :end_date => end_date
    )
    # Just for reference, sorting descending by Report is done by:   :sort => '-Report'
  end

  # query index
  def self.query_index(profile, start_date, end_date)
    Report.by_index_in_path_level_1.results(profile,
                                               :start_date => start_date,
                                               :end_date => end_date
    )
  end

  # get pageviews
  def self.get_pageview(profile, start_date, end_date)
    pageviews = []
    Report.query(profile, start_date, end_date).each do |result|
      # Just print the pageviews & unique-pageviews, for example
      pageviews << result.try(:pageviews)
      # puts result.try(:uniquePageviews)
    end
    pageviews = pageviews.map(&:to_i)
    return pageviews.inject(:+)
  end

  # get session count
  def self.get_session_count(profile, start_date, end_date)
    sessions = []
    Report.query(profile, start_date, end_date).each do |result|
      # Just print the session count
      sessions << result.try(:sessionCount)
    end
    sessions = sessions.map(&:to_i)
    return sessions.inject(:+)
  end

  # get session count
  def self.get_user_count(profile, start_date, end_date)
    users = []
    Report.query(profile, start_date, end_date).each do |result|
      # Just print the session count
      users << result.try(:users)
    end
    users = users.map(&:to_i)
    return users.inject(:+)
  end
end

app/controllers/reports_controller.rb
require 'net/http'
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    google_access_token
  end

  
  # GET access auth token
  # GET response json
  def outh_response
    @reports = Report.all
    begin
      access_token = $client.auth_code.get_token(params[:code], :redirect_uri => 'http://localhost:3000/oauth2callback')
      @response_json = access_token.get('https://www.googleapis.com/analytics/v3/management/accounts').body
      user = Legato::User.new(access_token)
      profile = user.profiles.first
      @users = Report.get_user_count(profile, 1.month.ago, 0.month.ago)
      @sessions = Report.get_session_count(profile, 1.month.ago, 0.month.ago)
      @pageviews = Report.get_pageview(profile, 1.month.ago, 0.month.ago)
      @name = user.profiles.map(&:name).first
      @names = user.profiles.map(&:name)
      render :index
    rescue
      respond_to do |format|
        format.html {render :index, alert: 'Analytics not found.' }
      end
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:page_view, :sessions, :date, :site_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_analytics.html.erb
<div class="get_analytics">
    <%= form_tag reports_path(@reports), :method => :get , id: "" do %>
        <%= select_tag "Account", options_for_select(@names.collect {|x| [x]}), :class =>"btn btn-default" rescue nil %>
        <%= submit_tag 'Day Data', :class =>"btn btn-default" %>
        <%= submit_tag 'Week Data', :class =>"btn btn-default" %>
        <%= submit_tag 'Month Data', :class =>"btn btn-default" %>
    <% end %>
</div>

<div class="dash-margin">
    <h5>Analytics account: <b><%= @name %></b></h5>
    <p>
      <h5>Users : <b><%= @users rescue 0 %></b>&nbsp; Sessions : <b><%= @sessions rescue 0 %></b>&nbsp; Pageviews : <b><%= @pageviews rescue 0 %></b></h5>
    </p>
</div>

<div id="barchartdiv"></div>
<div class="container-fluid">
  <div class="row text-center" style="overflow:hidden;">
        <div class="col-sm-3" style="float: none !important;display: inline-block;">
            <label class="text-left">Angle:</label>
            <input class="chart-input" data-property="angle" type="range" min="0" max="60" value="30" step="1" />   
        </div>

        <div class="col-sm-3" style="float: none !important;display: inline-block;">
            <label class="text-left">Depth:</label>
            <input class="chart-input" data-property="depth5D" type="range" min="1" max="25" value="10" step="1" />
        </div>
        <div class="col-sm-3" style="float: none !important;display: inline-block;">
            <label class="text-left">Inner-Radius:</label>
            <input class="chart-input" data-property="innerRadius" type="range" min="0" max="80" value="0" step="1" />
        </div>
    </div>
</div>
<br/>
<div id="chartdiv"></div>
<div id="serialChalkChartdiv"></div>

<script type="text/javascript">
    $( document ).ready(function() {
        serialChart(<%=@users%>, <%=@sessions%>, <%=@pageviews %>);
        pieChart(<%=@users%>, <%=@sessions%>, <%=@pageviews %>);
        serialCalkGraph(<%=@users%>, <%=@sessions%>, <%=@pageviews %>);
    });

    jQuery('.chart-input').off().on('input change',function() {
        var property    = jQuery(this).data('property');
        var target      = chart;
        var value       = Number(this.value);
        chart.startDuration = 0;

        if ( property == 'innerRadius') {
            value += "%";
        }

        target[property] = value;
        chart.validateNow();
    });
</script>

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :page_view %>
    <%= f.input :sessions %>
    <%= f.input :date %>
    <%= f.input :site_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<div class="navbar-inner">
    <ul class="breadcrumb">
        <i class="icon-chevron-left hide-sidebar"><a rel="tooltip" title="Hide Sidebar" href="#">&nbsp;</a></i>
        <i style="display:none;" class="icon-chevron-right show-sidebar"><a rel="tooltip" title="Show Sidebar" href="#">&nbsp;</a></i>
        <li>
            <a href="#">Dashboard Control</a> <span class="divider"></span> 
        </li>
        <li>
            <a href="#">Dashboard</a> <span class="divider"></span> 
        </li>
        <li class="active">Analytics Report</li>
    </ul>
</div>

<div class="row-fluid">
  <!-- block -->
  <div class="block">
      <div class="navbar navbar-inner block-header">
          <div class="muted pull-left">Analytics chart</div>
          <div class="pull-right"><span class="badge badge-warning">View More</span></div>
      </div>
      <div class="block-content collapse in"> 
        <div class="span3">
          <%= render partial: "analytics" %>
        </div>
      </div>
  </div>
  <!-- /block -->
</div>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page view:</strong>
  <%= @report.page_view %>
</p>

<p>
  <strong>Sessions:</strong>
  <%= @report.sessions %>
</p>

<p>
  <strong>Date:</strong>
  <%= @report.date %>
</p>

<p>
  <strong>Site:</strong>
  <%= @report.site_id %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>