config/routes.rb
Rails.application.routes.draw do
  resources :reports

  root to: 'visitors#report'
  devise_for :users
  resources :users
  get '/oauth2callback' => 'reports#outh_response', as: 'reports_outh'
  get '/report'	=> 'visitors#report', as: 'vistors_reports'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Dashboard Panel', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!-- <li class="active"><%#= link_to 'Reports', reports_path %></li> -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li class="divider"></li>
    <li><a href="#">Separated link</a></li>
    <li class="divider"></li>
    <li><a href="#">One more separated link</a></li>
  </ul>
</li>
</ul>
<form class="navbar-form navbar-left" role="search">
<div class="form-group">
  <input type="text" class="form-control" placeholder="Search">
</div>
<button type="submit" class="btn btn-default">Submit</button>
</form>
<ul class="nav navbar-nav navbar-right">
<li><a href="#">About</a></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</li>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="row">
    <div class="sidebar">
        <div class="mini-submenu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </div>
        <div class="list-group">
            <span href="/" class="list-group-item bag-col">
                Dashboard controls
                <span class="pull-right" id="slide-submenu">
                    <i class="fa fa-times"></i>
                </span>
            </span>
            <%= link_to "Dashboard", reports_path, :class => "list-group-item  #{is_active('reports','outh_response')}" %>
            <%= link_to "Reports", vistors_reports_path, :class => "list-group-item #{is_active('visitors','report')}" %>
            <%= link_to "Status information", root_path, :class => "list-group-item #{is_active('visitors','index')}" %>
            <% if user_signed_in? %>
              <%= link_to 'Edit account', edit_user_registration_path, :class => "list-group-item #{is_active('devise/registrations','edit')}" %>
              <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', :class => "list-group-item #{is_active('devise/sessions','destory')}" %>
            <% else %>
              <%= link_to 'Sign in', new_user_session_path, :class => "list-group-item #{is_active('devise/sessions','new')}" %>
              <%= link_to 'Sign up', new_user_registration_path, :class => "list-group-item #{is_active('devise/registrations','new')}" %>
            <% end %>
        </div> 
    </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Boot App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Boot App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/amcharts.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/serial.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/themes/none.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/pie.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/serial.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/themes/chalk.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/funnel.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/themes/light.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <div>
          <div class="col-sm-3 col-md-3 pull-left">
           <%= render 'layouts/sidebar' %>
         </div>
         <div class="col-sm-9 col-md-9 pull-right">
            <%= render 'layouts/messages' %>
            <%= yield %>  
         </div>
       </div>
    </main>
  </body>
</html>